### ISSUE TITLE
Convert DropDownMenu to select element

### ISSUE THREAD

**Issue by renshenhe** [myxvisual/react-uwp#12]
Since `DropDownMenu` does not use `<select />` element and `<option />` element this does not allow the usage of keys making it difficult to locate a selection without reimplementing a value targeting handler event in `DropDownMenu`.  I am unsure whether the intentions of the design were  focused on limited number of values/options or an oversight when using an implementation of the `TextField`/`TextBox` component.

**Comment by myxvisual** [comment]
@renshenhe Sincerely, thanks for your feedback, I have recently used this library in two new projects, can really find some bugs, but I can not immediately fix these, because the new function to change the code too much, this project temporarily Only I hope you can be more inclusive, I hope to make this project better and more efficient.
I will try to get the components closer to the native web element.

**Comment by myxvisual** [comment]
@renshenhe Hi, i think best practice is to use select, which can give the component more flexibility.

links:
[Material-UI DropDownMenu](http://www.material-ui.com/#/components/dropdown-menu)
[Fabric DropDown](https://dev.office.com/fabric#/components/dropdown)
[Ant Design DropDown](https://ant.design/components/dropdown/)
